In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
import pandas as pd
tickers = pd.read_csv("tickers.csv")
tickers = ' '.join(tickers['Name'])
print(tickers)

AAL AAPL AAP ABBV ABC ABT ACN ADBE ADI ADM ADP ADSK ADS AEE AEP AES AET AFL AGN AIG AIV AIZ AJG AKAM ALB ALGN ALK ALLE ALL ALXN AMAT AMD AME AMGN AMG AMP AMT AMZN ANDV ANSS ANTM AON AOS APA APC APD APH APTV ARE ARNC ATVI AVB AVGO AVY AWK AXP AYI AZO A BAC BAX BA BBT BBY BDX BEN BF.B BHF BHGE BIIB BK BLK BLL BMY BRK.B BSX BWA BXP CAG CAH CAT CA CBG CBOE CBS CB CCI CCL CDNS CELG CERN CFG CF CHD CHK CHRW CHTR CINF CI CLX CL CMA CMCSA CME CMG CMI CMS CNC CNP COF COG COL COO COP COST COTY CPB CRM CSCO CSRA CSX CTAS CTL CTSH CTXS CVS CVX CXO C DAL DE DFS DGX DG DHI DHR DISCA DISCK DISH DIS DLR DLTR DOV DPS DRE DRI DTE DUK DVA DVN DWDP DXC D EA EBAY ECL ED EFX EIX EL EMN EMR EOG EQIX EQR EQT ESRX ESS ES ETFC ETN ETR EVHC EW EXC EXPD EXPE EXR FAST FBHS FB FCX FDX FE FFIV FISV FIS FITB FLIR FLR FLS FL FMC FOXA FOX FRT FTI FTV F GD GE GGP GILD GIS GLW GM GOOGL GOOG GPC GPN GPS GRMN GS GT GWW HAL HAS HBAN HBI HCA HCN HCP HD HES HIG HII HLT HOG HOLX HON HPE HPQ HP HRB HRL HRS HSIC HST HSY HUM IBM ICE IDXX IFF ILMN INCY INFO INTC INTU IPG IP IQV IRM IR ISRG ITW IT IVZ JBHT JCI JEC JNJ JNPR JPM JWN KEY KHC KIM KLAC KMB KMI KMX KORS KO KR KSS KSU K LB LEG LEN LH LKQ LLL LLY LMT LNC LNT LOW LRCX LUK LUV LYB L MAA MAC MAR MAS MAT MA MCD MCHP MCK MCO MDLZ MDT MET MGM MHK MKC MLM MMC MMM MNST MON MOS MO MPC MRK MRO MSFT MSI MS MTB MTD MU MYL M NAVI NBL NCLH NDAQ NEE NEM NFLX NFX NI NKE NLSN NOC NOV NRG NSC NTAP NTRS NUE NVDA NWL NWSA NWS OKE OMC ORCL ORLY OXY O PAYX PBCT PCAR PCG PCLN PDCO PEG PEP PFE PFG PGR PG PHM PH PKG PKI PLD PM PNC PNR PNW PPG PPL PRGO PRU PSA PSX PVH PWR PXD PX PYPL QCOM QRVO RCL REGN REG RE RF RHI RHT RJF RL RMD ROK ROP ROST RRC RSG RTN SBAC SBUX SCG SCHW SEE SHW SIG SJM SLB SLG SNA SNI SNPS SO SPGI SPG SRCL SRE STI STT STX STZ SWKS SWK SYF SYK SYMC SYY TAP TDG TEL TGT TIF TJX TMK TMO TPR TRIP TROW TRV TSCO TSN TSS TWX TXN TXT T UAA UAL UA UDR UHS ULTA UNH UNM UNP UPS URI USB UTX VAR VFC VIAB VLO VMC VNO VRSK VRSN VRTX VTR VZ V WAT WBA WDC WEC WFC WHR WLTW WMB WMT WM WRK WU WYNN WYN WY XEC XEL XLNX XL XOM XRAY XRX XYL YUM ZBH ZION ZTS

If you get an error in code below just re-install yfinance: pip install yfinance

In [0]:
tickers = "AAL AAPL ADBE ADP ADSK AKAM ALXN AMAT AMGN AMZN ATVI AVGO BBBY BIDU BMRN CA CELG CERN CHKP CHTR CMCSA COST CSCO CSX CTRP CTSH DISCA DISCK DISH DLTR EA EBAY ENDP ESRX EXPE FAST FB FISV FOX FOXA GILD GOOG GOOGL HSIC ILMN INCT INCY INTU ISRG JD KHC LBTYA LBTYK LlTC LMCA LMCK LRCX LVNTA MAR MAT MDLZ MNST MSFT MU MXIM MYL NCLH NFLX NTAP NTES NVDA NXPI ORLY PAYX PCAR PCLN PYPL QCOM QVCA REGN ROST SBAC SBUX SNDK SRCL STX SWKS SYMC TMUS TRIP TSCO TSLA TXN ULTA VIAB VOD VRSK VRTX WBA WDC WFM XLNX YHOO"

In [0]:
!pip install yfinance
import yfinance as yf 
data = yf.download(tickers, start="2015-06-15", end= "2016-06-16")['Close']

Collecting yfinance
  Downloading https://files.pythonhosted.org/packages/c2/31/8b374a12b90def92a4e27d0fc595fc43635f395984e36a075244d98bd265/yfinance-0.1.54.tar.gz
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.6/dist-packages (from yfinance) (1.0.3)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.6/dist-packages (from yfinance) (1.18.3)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.6/dist-packages (from yfinance) (2.21.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.6/dist-packages (from yfinance) (0.0.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20->yfinance) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20->yfinance) (2020.4.5.1)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20->yfinance) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas>=0.24->yfinance) (1.12.0)
Building wheels for collected packages: yfinance
  Building wheel for yfinance (setup.py) ... done
  Created wheel for yfinance: filename=yfinance-0.1.54-py2.py3-none-any.whl size=22409 sha256=b27f080914068f43ab229d5ddd9d1e1b9d1782b04256cc24d392aa11a7ebedc9
  Stored in directory: /root/.cache/pip/wheels/f9/e3/5b/ec24dd2984b12d61e0abf26289746c2436a0e7844f26f2515c
Successfully built yfinance
Installing collected packages: yfinance
Successfully installed yfinance-0.1.54
[*********************100%***********************]  103 of 103 completed

15 Failed downloads:
- LMCA: No data found for this date range, symbol may be delisted
- SNDK: No data found for this date range, symbol may be delisted
- VIAB: No data found, symbol may be delisted
- LVNTA: No data found for this date range, symbol may be delisted
- FOX: Data doesn't exist for startDate = 1434326400, endDate = 1466035200
- FOXA: Data doesn't exist for startDate = 1434326400, endDate = 1466035200
- CTRP: No data found, symbol may be delisted
- SYMC: No data found, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- LMCK: No data found, symbol may be delisted
- YHOO: No data found for this date range, symbol may be delisted
- QVCA: No data found for this date range, symbol may be delisted
- WFM: No data found for this date range, symbol may be delisted
- LLTC: No data found for this date range, symbol may be delisted
- CELG: No data found, symbol may be delisted

In [0]:
data

                  AAL        AAPL       ADBE  ...  WFM       XLNX  YHOO
Date                                          ...
2015-06-15  40.070000  126.919998  78.900002  ...  NaN  46.310001   NaN
2015-06-16  39.480000  127.599998  79.940002  ...  NaN  46.799999   NaN
2015-06-17  39.880001  127.300003  77.910004  ...  NaN  46.630001   NaN
2015-06-18  39.980000  127.879997  79.389999  ...  NaN  47.160000   NaN
2015-06-19  41.560001  126.599998  79.699997  ...  NaN  46.299999   NaN
...               ...         ...        ...  ...  ...        ...   ...
2016-06-09  33.400002   99.650002  98.070000  ...  NaN  47.029999   NaN
2016-06-10  33.139999   98.830002  97.089996  ...  NaN  46.730000   NaN
2016-06-13  31.799999   97.339996  96.959999  ...  NaN  46.320000   NaN
2016-06-14  30.360001   97.459999  96.980003  ...  NaN  46.959999   NaN
2016-06-15  30.490000   97.139999  97.019997  ...  NaN  46.689999   NaN

[254 rows x 103 columns]

In [0]:
data.to_csv('portfolio_data.csv')
files.download('portfolio_data.csv')